package com.lordabbett.csvParser.csvParser;

public class CSVConstants {

	public static String csv1 = "seq,first,last,age,street,city,state,zip,dollar,pick,date\r\n" + 
			"1,Christian_us-en,Bennett,60,Catto View,Ebiojuhuw,MT,20361,$6149.06,GREEN,09/29/2015\r\n" + 
			"2,Connor_us-en,Carpenter,33,Fogmoj Ridge,Omifupo,OK,97256,$5675.67,RED,11/09/2057\r\n" + 
			"3,Charlie_us-en,Wilkerson,44,Omopab Turnpike,Atavovi,NC,14590,$5955.94,BLUE,11/16/2034\r\n" + 
			"4,Jeffery_us-en,George,52,Lutut Boulevard,Tojzafli,LA,90163,$5865.90,WHITE,05/10/2016\r\n" + 
			"5,Ora_us-en,Porter,20,Cuvge Key,Ubgire,NC,18008,$2806.76,BLUE,08/30/1957\r\n" + 
			"6,Luke_us-en,West,38,Nuah Point,Juuplo,IA,88487,$3834.75,WHITE,06/01/2012\r\n" + 
			"7,Matilda_us-en,Marshall,20,Poiwe Pike,Unpiiri,GA,35829,$3248.84,WHITE,12/17/1994\r\n" + 
			"8,Addie_us-en,Walker,20,Igorih Circle,Ufbahapa,HI,79069,$1112.00,BLUE,01/28/1980\r\n" + 
			"9,Lucille_us-en,Brady,22,Ucbo Junction,Vuvufa,WA,33385,$1912.71,BLUE,08/20/1989\r\n" + 
			"10,Marvin_us-en,Gutierrez,34,Hosa Highway,Morfazlij,DE,67505,$967.95,YELLOW,11/27/2046\r\n" + 
			"";
	public static String csv2 = "code,lastPublished,type,content,tags,path,createdDate,createdBy,name,hasVariation,group\r\n" + 
			"DIS_000016_en-US,2018-01-26T03:23:01.346Z,Disclosure,\"The net expense is based on estimates for the current fiscal year and takes into account contractual fee waivers/expense reimbursements that currently are scheduled to remain in place through 02/28/2018. For periods when fees and expenses were waived and/or reimbursed, the Fund benefited by not bearing such expenses. Without such fee waivers/ reimbursements, performance would have been lower.\",\"classifications,global-equity,global-core-equity,legal-disclosure:CapXRef/classifications/global-&-international/global-equity/mutual-funds/global-core-equity,global-&-international,mutual-funds\",/content/dam/lord-abbett/disclosure/DIS_000016_en-US,2017-12-28T16:11:26.028Z,admin,Expense Ratio - Global Core Equity Fund,false,Disclosure\r\n" + 
			"DIS_000031_en-US,2018-01-26T03:23:01.345Z,Disclosure,\"The net expense ratio takes into account contractual fee waivers/expense reimbursements that currently are scheduled to remain in place through 04/30/2018. For periods when gross expenses exceeded the cap, the Fund benefited by not bearing certain expenses. Without such fee waivers/reimbursements, performance would have been lower.\",\"legal-disclosure:CapXRef/classifications/u.s.-equity/dividend-growth/series-funds/ins.-series-calibrated-div.-gr,legal-disclosure:CapXRef/classifications/taxable-fixed-income/short-duration-credit/series-funds/series-short-duration-income-,share-class,ins.-series-bond,international-core,legal-disclosure:CapXRef/classifications/u.s.-equity/smid-cap-value/series-funds/ins.-series-value-opp,ins.-series-total-return,taxable-fixed-income,multi-sector,global-&-international,ins.-series-fundamental-equity,u.s.-equity,series-short-duration-income-,mid-cap-growth,ins.-series-gr-opps,legal-disclosure:CapXRef/classifications/u.s.-equity/large-cap-core/series-funds/ins.-series-classic-stock,legal-disclosure:CapXRef/classifications/u.s.-equity/mid-cap-growth/series-funds/ins.-series-gr-opps,series-funds,legal-disclosure:CapXRef/share-class/share-class-vc,core-plus-total-return,share-class-vc,smid-cap-value,small-cap-growth,legal-disclosure:CapXRef/classifications/taxable-fixed-income/core-plus-total-return/series-funds/ins.-series-total-return,international-small-cap,large-cap-core,ins.-series-international-equi,ins.-series-value-opp,legal-disclosure:CapXRef/classifications/u.s.-equity/small-cap-growth/series-funds/ins.-series-dev-growth,large-cap-value,classifications,short-duration-credit,legal-disclosure:CapXRef/classifications/global-&-international/international-core/series-funds/ins.-series-international-equi,dividend-growth,legal-disclosure:CapXRef/classifications/taxable-fixed-income/multi-sector/series-funds/ins.-series-bond,legal-disclosure:CapXRef/classifications/u.s.-equity/large-cap-value/series-funds/ins.-series-fundamental-equity,legal-disclosure:CapXRef/classifications/global-&-international/international-small-cap/series-funds/ins.-series-intl-opps,ins.-series-dev-growth,ins.-series-intl-opps,ins.-series-classic-stock,ins.-series-calibrated-div.-gr\",/content/dam/lord-abbett/disclosure/DIS_000031_en-US,2017-12-29T16:35:49.787Z,admin,Expense Ratio - Series Funds,false,Disclosure\r\n" + 
			"DIS_000152_en-US,2018-02-23T17:31:27.030Z,Disclosure,\"A Note about Risk: The value of investments in equity securities will fluctuate in response to general economic conditions and to changes in the prospects of particular companies, including market, liquidity, currency, and political risks. Mid and small cap company stocks tend to be more volatile and may be less liquid than large cap company stocks. Mid and small cap companies also may have more limited product lines, markets, or financial resources and typically experience a higher risk of failure than large companies. However, larger companies may have slower rates of growth than smaller successful companies. Investments in growth companies can be more sensitive to the company's earnings and more volatile than the stock market in general. Non-U.S. investments in which the Fund may invest present increased market, liquidity, currency, political, information, and other risks. These risks can be greater in the case of emerging country securities. The Fund engages in active and frequent trading of its securities, which may result in increased transaction fees, reduced investment performance, and higher taxes. These factors can affect Fund performance. As it is a newly organized fund, the Fund's performance at this time is very limited. The Fund's performance achieved during this initial period of investment operations may not be replicated over longer periods and may not be indicative of how the Fund will perform in the future.\",\"legal-disclosure:CapXRef/classifications/global-&-international/global-equity/passport-portfolios/global-core-equity-ucits,classifications,global-equity,passport-portfolios,global-core-equity-ucits,global-&-international\",/content/dam/lord-abbett/disclosure/DIS_000152_en-US,2018-02-23T17:29:29.768Z,KGAFFNEY@LordAbbett.com,A Note About Risk UCITS Global Core Equity Fund,false,Disclosure\r\n" + 
			"DIS_000196_en-US,2018-03-02T20:59:46.532Z,Disclosure,\"A Note about Risk: The value of investments in equity securities will fluctuate in response to general economic conditions and to changes in the prospects of particular companies, including market, liquidity, currency, and political risks. Mid and small cap company stocks tend to be more volatile and may be less liquid than large cap company stocks. Mid and small cap companies also may have more limited product lines, markets, or financial resources and typically experience a higher risk of failure than large companies. However, larger companies may have slower rates of growth than smaller successful companies. Investments in growth companies can be more sensitive to the company's earnings and more volatile than the stock market in general. Non-U.S. investments in which the Fund may invest present increased market, liquidity, currency, political, information, and other risks. These risks can be greater in the case of emerging country securities. The Fund engages in active and frequent trading of its securities, which may result in increased transaction fees, reduced investment performance, and higher taxes. These factors can affect Fund performance. As it is a newly organized fund, the Fund's performance at this time is very limited. The Fund's performance achieved during this initial period of investment operations may not be replicated over longer periods and may not be indicative of how the Fund will perform in the future\",\"legal-disclosure:CapXRef/classifications/global-&-international/global-equity/passport-portfolios/global-core-equity-ucits,classifications,global-equity,legal-disclosure:used-in,fact-sheets,passport-portfolios,global-core-equity-ucits,global-&-international,legal-disclosure:used-in/fact-sheets\",/content/dam/lord-abbett/disclosure/DIS_000196_en-US,2018-03-02T20:49:24.631Z,KGAFFNEY@LordAbbett.com,UCITS Risk Disclosure - Global Core Equity Fund,false,Disclosure\r\n" + 
			"DIS_000200_en-US,2018-03-05T17:52:52.121Z,Disclosure,\"A Note about Risk: The value of investments in equity securities will fluctuate in response to general economic conditions and to changes in the prospects of particular companies and/or sectors in the economy. The foreign securities in which the Fund primarily invests generally pose greater risks than domestic securities, including greater price fluctuations and higher transaction costs. Foreign investments also may be affected by changes in currency rates or currency controls. With respect to certain foreign countries, there is a possibility of nationalization, expropriation or confiscatory taxation, imposition of withholding or other taxes, and political or social instability that could affect investments in those countries. These risks can be greater in the case of emerging country securities. Investments in either growth or value stocks may shift in and out of favor for long periods of time, depending on market and economic conditions. The Fund is subject to the risks associated with derivatives, which may be different from and greater than the risks associated with investing directly in securities and other investments. The Fund may invest in exchange-traded funds (“ETFs”), investments in ETFs are subject to a variety of risks, including the risks associated with a direct investment in the underlying securities that the ETF holds. \",\"classifications,global-equity,global-core-equity,legal-disclosure:CapXRef/classifications/global-&-international/global-equity/mutual-funds/global-core-equity,global-&-international,mutual-funds\",/content/dam/lord-abbett/disclosure/DIS_000200_en-US,2018-03-05T17:52:07.375Z,ALEHMKUHL@LordAbbett.com,Risk Disclosure - Global Core Equity Fund,false,Disclosure\r\n" + 
			"DIS_000203_en-US,2018-03-05T18:49:32.706Z,Disclosure,\"The net expense ratio takes into account contractual fee waivers/expense reimbursements that currently are scheduled to remain in place through 02/28/2019. For periods when fees and expenses were waived and/or reimbursed, the Fund benefited by not bearing such expenses. Without such fee waivers/reimbursements, performance would have been lower.\",\"classifications,legal-disclosure:CapXRef/classifications/global-&-international/international-dividend/mutual-funds/intl-dividend-income-fund,intl-dividend-income-fund,global-&-international,international-dividend,mutual-funds\",/content/dam/lord-abbett/disclosure/DIS_000203_en-US,2018-03-05T18:48:31.916Z,ALEHMKUHL@LordAbbett.com,Expense Ratio - International Dividend Income Fund,false,Disclosure\r\n" + 
			"DIS_000204_en-US,2018-03-05T19:02:47.818Z,Disclosure,\"The net expense ratio takes into account contractual fee waivers/expense reimbursements that currently are scheduled to remain in place through 02/28/2019. For periods when fees and expenses were waived and/or reimbursed, the Fund benefited by not bearing such expenses. Without such fee waivers/reimbursements, performance would have been lower.\",\"classifications,international-core,international-equity,legal-disclosure:CapXRef/classifications/global-&-international/international-core/mutual-funds/international-equity,global-&-international,mutual-funds\",/content/dam/lord-abbett/disclosure/DIS_000204_en-US,2018-03-05T19:01:39.506Z,ALEHMKUHL@LordAbbett.com,Expense Ratio - International Equity Fund,false,Disclosure\r\n" + 
			"DIS_000199_en-US,2018-03-05T17:50:56.302Z,Disclosure,The Fund seeks long-term growth of capital by investing in stocks of both U.S. and non-U.S. companies.,\"classifications,global-equity,global-core-equity,legal-disclosure:CapXRef/classifications/global-&-international/global-equity/mutual-funds/global-core-equity,global-&-international,mutual-funds\",/content/dam/lord-abbett/disclosure/DIS_000199_en-US,2018-03-05T17:50:03.989Z,ALEHMKUHL@LordAbbett.com,Fund Goal - Global Core Equity Fund,false,Disclosure";
}
